### PR TITLE
Fixed JsonNumber implementations #equals

### LINKED ISSUE #12: Give more sensible equality semantics for JsonNumber
Right now `JsonNumber.of(123)` will not equal `JsonNumber.of(new BigInteger("123"))` and that feels...strange?

### PR DESCRIPTION
**Pull request by java-coding-prodigy**
Fixes #12

### CODE REVIEW

**Comment by bowbahdoe** [comment]
@java-coding-prodigy Can you write some unit tests for this?

Also as implemented can you make sure that equality would be reflexive?

I.E. in 

```
a.equals(b);
```

`b` and `a` should be able to be swapped without causing an issue.

**Comment by java-coding-prodigy** [comment]
Hmm, you are right, this won't work.
But it looks like we will have to use pattern matching in every one of them, unless I am missing something.
I think using `isIntegral()` would help, but I'll have to think about it.

**Comment by bowbahdoe** [comment]
One thing to look at would be how clojure's `=` and `hash` works on numbers.

https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/Numbers.java

**Comment by java-coding-prodigy** [comment]
Bump

**Comment by bowbahdoe** [comment]
Sorry - can you rebase onto main/merge main into your branch? I made it so tests will run that way.

Also, add unit tests for the reflexive behavior thing. I don't know if the change you made is enough

**Comment by bowbahdoe** [comment]
Also in the future I don't mind if you @ me to get my attention. @java-coding-prodigy

**Comment by bowbahdoe** [comment]
@java-coding-prodigy just a reminder about this. Totally fine if you forgot, I don't mind leaving this up until one of us has time

**Comment by bowbahdoe** [comment]
This should be resolved now that the number impls store strings and compare bigdecimal representations

**Pull request closed without merging**
